// Export all fill utility functions
export { getFillType } from "./get-fill-type";
export { getGradientFill } from "./get-gradient-fill";
export { getPicFill } from "./get-pic-fill";
export { getBgPicFill } from "./get-bg-pic-fill";
export { getPatternFill } from "./get-pattern-fill";
export { getLinerGrandient } from "./get-liner-grandient";
export { getBgGradientFill } from "./get-bg-gradient-fill";
export { getShapeFill } from "./get-shape-fill";
export { getSlideBackgroundFill } from "./get-slide-background-fill";
